# Generated by Django 4.2.30 on 2026-09-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
    ]
