# Generated by Django 4.2.30 on 2026-09-20 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_account_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.CharField(blank=True, help_text='URL name or absolute URL', max_length=200)),
                ('icon_svg', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='finance.navigationitem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DashboardModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('module_type', models.CharField(choices=[('stat_balance', 'Total Balance Stat'), ('stat_income', 'Monthly Income Stat'), ('stat_expense', 'Monthly Expense Stat'), ('chart_income_expense', 'Income vs Expenses Chart'), ('chart_spending_category', 'Spending by Category Chart')], max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='finance.dashboardmodule')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
